//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IF.Lastfm.Core.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrackApiResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrackApiResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IF.Lastfm.Core.Tests.Resources.TrackApiResponses", typeof(TrackApiResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TrackGetShouts {
            get {
                object obj = ResourceManager.GetObject("TrackGetShouts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TrackGetShoutsEmpty {
            get {
                object obj = ResourceManager.GetObject("TrackGetShoutsEmpty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TrackGetShoutsError {
            get {
                object obj = ResourceManager.GetObject("TrackGetShoutsError", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TrackGetShoutsSingle {
            get {
                object obj = ResourceManager.GetObject("TrackGetShoutsSingle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TrackScrobbleBadAuthError {
            get {
                object obj = ResourceManager.GetObject("TrackScrobbleBadAuthError", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method=track.scrobble&amp;api_key=59dd1140db864fd4a68ca820709eaf98&amp;api_sig=722818CCD472F3EB0CF079F7AC543077&amp;format=json&amp;artist[0]=Rubies&amp;album[0]=Stand in a Line&amp;track[0]=Teppan-Yaki (A Collection of Remixes)&amp;albumArtist[0]=Schinichi Osawa&amp;chosenByUser[0]=0&amp;timestamp[0]=1330528563&amp;artist[1]=Broken Social Scene&amp;album[1]=Sentimental X&apos;s&amp;track[1]=Forgiveness Rock Record&amp;albumArtist[1]=Broken Social Scene&amp;chosenByUser[1]=0&amp;timestamp[1]=1330528923&amp;artist[2]=Björk&amp;album[2]=Hyperballad&amp;track[2]=Post&amp;albumArtist[2]=Bjö [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TrackScrobbleMultipleRequestBody {
            get {
                return ResourceManager.GetString("TrackScrobbleMultipleRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method=track.scrobble&amp;api_key=59dd1140db864fd4a68ca820709eaf98&amp;api_sig=9162EC581974F03444D2C1C9C808013B&amp;format=json&amp;artist[0]=65daysofstatic&amp;album[0]=The Fall of Math&amp;track[0]=Hole&amp;api_key=59dd1140db864fd4a68ca820709eaf98&amp;chosenByUser[0]=1&amp;timestamp[0]=1330530003&amp;method=track.scrobble&amp;sk=071a119a9aac4942b1b05328a5591f55.
        /// </summary>
        public static string TrackScrobbleSingleRequestBody {
            get {
                return ResourceManager.GetString("TrackScrobbleSingleRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TrackScrobbleSuccess {
            get {
                object obj = ResourceManager.GetObject("TrackScrobbleSuccess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method=track.scrobble&amp;api_key=59dd1140db864fd4a68ca820709eaf98&amp;api_sig=785ACDF92D29CF6953845E271DF9597C&amp;format=json&amp;artist[0]=やくしまるえつこ&amp;album[0]=X次元へようこそ&amp;track[0]=X次元へようこそ&amp;albumArtist[0]=やくしまるえつこ&amp;chosenByUser[0]=0&amp;timestamp[0]=1330529643&amp;artist[1]=65daysofstatic&amp;album[1]=The Fall of Math&amp;track[1]=Hole&amp;api_key=59dd1140db864fd4a68ca820709eaf98&amp;chosenByUser[1]=1&amp;timestamp[1]=1330530003&amp;method=track.scrobble&amp;sk=071a119a9aac4942b1b05328a5591f55.
        /// </summary>
        public static string TrackScrobbleTwoRequestBody {
            get {
                return ResourceManager.GetString("TrackScrobbleTwoRequestBody", resourceCulture);
            }
        }
    }
}
