name: Build & Test

on:
  push:
    branches-ignore:
    - release
    paths-ignore:
    - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies IF.Lastfm.sln
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore IF.Lastfm.sln
    - name: Test
      run: dotnet test --no-restore IF.Lastfm.sln
