name: Build & Test

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches-ignore: [ release ]
    types: [ opened, reopened, ready_for_review, synchronised ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-restore
